### ISSUE TITLE
CRASHED AND DELETE PLUG...it's crazy?

### ISSUE THREAD

**Issue by manuelsongokuh** [devernay/openfx-misc#33] opened 2015-08-08 23:31 UTC
hello devernay
i find dangerous...so
i added nodes:
-1 "noise" (NoiseOFX: Generate simple noise.)
-1 "plasma" (PlasmaCImg: Generate plasma noise.)
-1 viewer, linked number 2 (1 for noise, 2 for plasma)
-frame project from 1 to 10, frame range : 1 to 10
-play forward with continuous.
-i press 1 (play worked)
-i press 2 (play worked) after 4 seeconds is CRASHED..
-reopen Natron and windows said: plug plasma not found...
-i check plug "plasma" is disappeared..
i check folder of natron and plugs folders, is missed "plasma"...
this is crazy for delete file?!
natron :0f75b8a1ba0138799d85a065694f27bd21696a84.

you check it ok?

**Comment by manuelsongokuh** [comment] 2015-08-08 23:33
"ERROR: The node net.sf.cimg.CImgPlasma version 2.0 was found in the script but does not exist in the loaded plug-ins."

**Comment by manuelsongokuh** [comment] 2015-08-08 23:40
i can screen record....a moment

**Comment by olear** [comment] 2015-08-08 23:46
https://github.com/MrKepzie/Natron/issues/821

**Comment by manuelsongokuh** [comment] 2015-08-08 23:48
ah ok, that is bug..ok i will wait for FIX it ok?
thank you

**Comment by devernay** [comment] 2015-08-09 17:11
Duplicate of MrKepzie/Natron#821

**Closed by devernay** 2015-08-09 17:11 UTC
Labels: duplicate
